### ISSUE TITLE
Preview fields are not displayed in the specified order.

### ISSUE THREAD

**Issue by streamtree** [redpanda-data/kowl#358] opened 2022-04-30 06:27 UTC
When using preview fields, the definition dialog allows the fields to be dragged and dropped into a particular order. This order is ignored in the UI and some kind of preset order is used instead.

**Comment by rikimaru0345** [comment] 2022-05-23 17:04
should now be fixed in 905ce28489bf0e46ab349a12da837ac2767ce5ad

thanks for reporting!

**Comment by rikimaru0345** [comment] 2022-05-23 17:04
please let me know if it works for you as intended now 😄

**Closed** 2022-06-01 15:03 UTC
Labels: bug, frontend
