### ISSUE TITLE
Data lineage

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/kowl#342] opened 2022-04-05 03:28 UTC
This would be a new feature giving users details on how messages flow through producers, to various topics, possibly data transformation nodes, and on to consumers. Other tools that focus on data lineage (but not necessarily compatible with event-driven systems):

- [Informatica](https://www.informatica.com)
- [Manta](https://getmanta.com)
- Apache Atlas
- [Atlan](https://atlan.com/platform/data-lineage-governance/)
- Watson Knowledge Catalog
- others...

With Redpanda integration, metadata related to wasm transforms and the resulting topic could be discoverable by Kowl.

**Comment by weeco** [comment] 2022-04-05 09:05
hey @vuldin thanks for filing these requests. I think this specific one might be a duplicate of https://github.com/redpanda-data/kowl/issues/130 if I understand it correctly.

The main problem we had is that the information what topics a client produced is not available to use - unless the existing producers implement something specifically (e.g. additional headers, a library that pushes information about what they produce etc). That was not satisfying enough in my opinion.

**Comment by vuldin** [comment] 2022-04-05 09:39
I wondered where this metadata would come from. I need to look more into how other tools handle this.

Thanks for linking the other issue! That does seem to cover data lineage, but I didn't find it since data lineage wasn't mentioned (I'll change that soon).

**Closed** 2022-04-05 09:48 UTC
